### ISSUE TITLE
Document the artwork sources

### ISSUE THREAD

**Issue by samreid** [phetsims/estimation#5]
Where did this art come from?  I am seeing many things in assets/ so perhaps we drew it.  @jbphet committed it so I should check with him.

**Comment by samreid** [comment]
@jbphet can you confirm my changes above?

**Comment by jbphet** [comment]
All artwork was drawn by me.  The sim was abandoned before any of the icons were finalized, so I hadn't gotten 'round to making sure the license info was good.  I'll add myself as author to avoid any further confusion and close this issue.
