### ISSUE TITLE
replace MyHSlider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/estimation#7]
MySlider is a copy of HSlider. No idea why, there's just a TODO item in the code that says:

> TODO This is a copy of sun.HSlider, it should be removed.

No idea who is responsible for this sim. It's not published, so not in https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md.

**Comment by pixelzoom** [comment]
3+ years later, MySlider was still there. And it was impeding my progress on https://github.com/phetsims/scenery/issues/1078.  I didn't want to spend time converting input listener for a class that shouldn't exist.  I tried replacing it with an HSlider, and I saw no difference.   So I went ahead and deleted MyHSlider. 

@jbphet please review.

**Comment by jbphet** [comment]
Looks reasonable to me.  Closing.
